### ISSUE TITLE
Doesn't appear to work in OS X 10.9 / ST 2.0.2, 2221

### ISSUE THREAD

**Issue by joeyfigaro** [bistory/Sublime-Minifier#15]
Using the hotkey doesn't do anything and the minify option is unavailable in the menu.

**Comment by MacKentoch** [comment]
had same problem : 
> #### be sure you cloned or install in **~/Library/Application Support/Sublime Text X/Packages**

and (where was my problem)
>#### be sure **folder is named "Minifier"**

after clone from git it was call "sublime-Minifier" <-> won't work if so

**Comment by bistory** [comment]
Local uglifyJS is not used in this plugin so no npm install will resolve you issues.
@MacKentoch is right, check your folder name first...
