### ISSUE TITLE
HTTP error 400 contacting API

### ISSUE THREAD

**Issue by codehate** [bistory/Sublime-Minifier#18]
---------------------------
Sublime Text
---------------------------
Minifier Error: HTTP error 400 contacting API

Any solution?

**Comment by bistory** [comment]
Hi !
It sometimes happens when the online service is not responding.
Uglifyjs online seems down at the moment : https://marijnhaverbeke.nl/uglifyjs

**Comment by yinzhixin** [comment]
I have seen this problem before,because there is something wrong with js grammar
