### ISSUE TITLE
Uglify and Console.log removal

### ISSUE THREAD

**Issue by BenRacicot** [bistory/Sublime-Minifier#19]
Firstly, hello and thanks for making this plugin.
[This article](http://jstarrdewar.com/blog/2013/02/28/use-uglify-to-automatically-strip-debug-messages-from-your-javascript/) explains how to use Uglify's 'Dead code' remover to remove all the console.logs

Can you guide me on how to use this with your SublimeText package?

**Comment by bistory** [comment]
There is no such option in the HTTP API so there is no way to achieve your goal, sorry...
