### ISSUE TITLE
Minifier Error: HTTP error 502 contacting API

### ISSUE THREAD

**Issue by DrPrez** [bistory/Sublime-Minifier#20]
Hello,

Thank you for an awesome package. 

These last few days I've run into different problems, a few days ago I kept getting HTTP error 500 and now today I keep getting "HTTP error 502 contacting API".

I have tried restarting computer, Sublime Text 3 and also changing to a different Internet provider, but the problem is still there :(

I'm guessing there is a server problem somewhere, are there more stable servers out there we can use instead?

Please advise.

**Comment by bistory** [comment]
Hi !
It sometimes happens when the online service is not responding.
Uglifyjs online seems down at the moment : https://marijnhaverbeke.nl/uglifyjs

**Comment by DrPrez** [comment]
Thanks for the replay bistory.

Do you know of any alternative servers we can use while https://marijnhaverbeke.nl/uglifyjs has problems? If so, is it possible to add in the code that if first server doesn't respond, try other servers?

**Comment by bistory** [comment]
You can still use Google Closure Compiler which is included in the tool.

**Comment by DrPrez** [comment]
Unfortunately google_closure has never worked for me, I get "There was an error minifying the file." whenever I set "compiler": "google_closure"

**Comment by bistory** [comment]
Then there is no alternative way, sorry...
You can still improve your skills and use Grunt JS :)

**Comment by DrPrez** [comment]
Thanks for your assistance, appriciate it.

:+1:
