### ISSUE TITLE
speed

### ISSUE THREAD

**Issue by paulyn000** [bistory/Sublime-Minifier#25]
First of, thanks a lot and a very good job. I don't have any problems just want to  but I guess you could improve the speed I've got 3000 codes and it takes much time. thought it's alright. thanks again

**Comment by bistory** [comment]
Hi,
Speed could not be improved as it depends on public HTTP API.
If you want to improve the speed of minifying for 3000 files, you should seriously consider using Gulp and UglifyJS locally.
