### ISSUE TITLE
There was an error minifying the file.

### ISSUE THREAD

**Issue by CodeZeno** [bistory/Sublime-Minifier#34]
70% of the time when using **ctrl + alt + shift + m** I get the message:

> There was an error minifying the file.

I have to keep doing it until it is successful, I don't change any code just keep pressing **ctrl + alt + shift + m** until it is successful.

How do I troubleshoot the error?

Here are my settings:

```
{
  "remove_new_lines": false,
  "optimization_level": "SIMPLE_OPTIMIZATIONS",
  "compiler": "google_closure",
  "css_compiler": "cssminifier",
  "open_on_min": false,
  "timeout": 10,
  "minify_options": {
    "ask_file_name": false,
    "default_name": null,
    "suffix": ".min"
  }
}
```

**Comment by CodeZeno** [comment]
Ah I didn't realise it needed an internet connection, that would explain the speed.
I am now using a custom build system:

**Google Closure.sublime-build**
```
{
   "cmd": [
      "java",
      "-jar",
      "${packages}/Google Closure/closure-compiler-v20181008.jar",
      "--js",
         "$file",
      "--js_output_file",
         "$file_path/$file_base_name.min.js",
      "--compilation_level",
         "SIMPLE_OPTIMIZATIONS",
      "--create_source_map",
         "$file_base_name.min.js.map",
      "--source_map_location_mapping",
         "${file_path}|.",
      "--output_wrapper",
         "%output%\r\n//# sourceMappingURL=./$file_base_name.min.js.map"
   ],
   "file_regex": "^(.*):([0-9]+):() ERROR - (.*)",
   "selector": "source.js"
}
```

[https://developers.google.com/closure/compiler/](https://developers.google.com/closure/compiler/)

**Comment by bistory** [comment]
Yes it uses internet connection to avoid relying on dependancies.
As an offline alternative, I recommend Gulp or webpack that can do far more things than this plugin.
